const tomato = [{
        diseases: "Fungal",
        symptoms: "Fruit symptoms are the most common although stem, leaves and roots can also be infected; disease causes characteristic sunken circular lesions on the fruit; the indentations on may have visible concentric brown and yellow rings; lesion centers turn tan in color as they mature and become dotted with small black fungal fruiting bodies (microsclerotia); lesions can grow very large",
        causes: "Fungus",
        comments: "Disease emergence favors warm weather; appears early in the spring",
        management: "Avoid sprinkler irrigation when fruit is ripening; rotate crops with other non-solanaceous plants",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/4130/file/default-2a1eb8006ef840a1a31ac4c78676985f.jpg",
    },

    {
        diseases: "Black mold",
        symptoms: "Disease causes the appearance of black or brown lesions on the surface of ripe fruit; lesions may be tiny flecks or may be large patches of decaying tissue; during periods of humid weather, the lesions may become covered in black, velvety spore masses",
        causes: "Fungus",
        comments: "Disease is found wherever tomatoes are grown; ripe fruit become increasingly susceptible to the fungus the longer they stay on the vine after ripening.",
        management: "Cultural control methods such as avoiding wetting the foliage when watering and harvesting fruits as soon as they are ripe can help to reduce the incidence of the disease; in areas where disease is a persistent problem, chemical control may be necessary with an appropriate fungicide; fungicide is usually applied 4-6 weeks prior to the first anticipated fruit harvest",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/63644/file/default-f5ab729e1e0952c8e3fe1c542f252a70.jpg",
    },
    {
        diseases: "Early blight",
        symptoms: "Early blight symptoms start as oval shaped lesions with a yellow chlorotic region across the lesion; concentric leaf lesions may be seen on infected leaves; leaf tissue between veins is destroyed; severe infections can cause leaves to completely collapse; as the disease progresses leaves become severely blighted leading to reduced yield; tomato stems may become infected with the fungus leading to Alternaria stem canker; initial symptoms of of stem canker are the development of dark brown regions on the stem; stem cankers may enlarge to girdle the whole stem resulting in the death of the whole plant; brown streaks can be found in the vascular tissue above and below the canker region; fruit symptoms include small black v-shaped lesions at the shoulders of the fruit (the disease is also known black shoulder); lesions may also appear on the fruit as dark flecks with concentric ring pattern; fruit lesions can seen in the field or may develop during fruit transit to the market; the lesions may have a velvety appearance caused by sporulation of the fungus",
        causes: "Fungus",
        comments: "Disease can spread rapidly after plants have set fruit; movement of air-borne spores and contact with infested soil are causes for the spread of the diseaseDisease emergence favors warm weather; appears early in the spring",
        management: "Apply appropriate fungicide at first sign of disease; destroy any volunteer solanaceous plants (tomato, potato, nightshade etc); practice crop rotations",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/4139/file/default-e772298db25892b493585eb72d6776c1.jpg",
    },

    {
        diseases: "Fusarium wilt",
        symptoms: "Symptoms of Fusarium wilt may first appear as yellowing and wilting of leaves on one side of the leaf midrib or plant; one-sided symptoms are caused by a blockage in the vascular system supplying the symptomatic side of the plant; as the disease progresses, older leaves become necrotic and the plant begins to wilt; fruit on infected plants is smaller and yield is reduced; damage to leaves makes fruit susceptible to sunscald; stem symptoms may be mistaken for bacterial wilt but a bacterial ooze test will be negative; stem tissue becomes discolored brown",
        causes: "Fungus",
        comments: "Disease emergence favors warm, moist soil Fusarium wilt is not a major issue in tomato production, however, the disease can still cause minor losses",
        management: "Plant resistant varieties; sanitize all equipment regularly; control root knot nematodes; rotate crops away from tomato for several years",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/4147/file/default-394102fda04dc2906e0e31bde2f976ce.jpg",
    },

    {
        diseases: "Gray mold (Botrytis blight)",
        symptoms: "Disease appears on tomato seedlings at or just below the soil line as a fuzzy gray-brown lesion which often girdles the stem, if stem is girdled all parts of the plant above the lesion begin to wilt; infected flowers and calyxes become covered in gray spores; unripe fruit turns light brown or gray in color and rots; green fruit infected by airborne spores develop circular white rings called “ghost spots”.",
        causes: "Fungus",
        comments: "Gray mold is usually associated with wounds on plants; can develop in relatively cool conditions.",
        management: "Liming soil to increase calcium content can help to reduce plant susceptibility to gray mold; application of appropriate fungicide prior to formation of dense canopy.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/63659/file/default-48f06c91f5bfe5e434d89d76c91e78ac.jpg",
    },
    {
        diseases: "Leaf Mold ",
        symptoms: "The older leaves exhibit pale greenish to yellow spots (without distinguishable margins) on upper surface. Whereas the lower portion of this spots exhibit green to brown velvety fungal growth. As the disease progress the spots may coalesce and appear brown. The infected leaves become wither and die but stay attached to the plant. The fungus also infects flowers and fruits. The affected flowers become black and drop off. The affected fruit intially shows smooth black irregular area on the stem end but later it becomes sunken, leathery and dry.”.",
        causes: "Fungus",
        comments: "The disease is favored by high relative humidity. Also a common disease in green house tomato crop.",
        management: "Grow available resistant varieties. Avoid leaf wetting and overhead application of water. Follow proper spacing to provide good air circulation around the plants. Remove the infected plant debris and burn them. If the disease is severe scary suitable fungicide.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/63616/file/default-fcdcc0914dbf2813e91de329afb2af7c.jpg",
    },
    {
        diseases: "Septoria leaf spot ",
        symptoms: "Symptoms may occur at any stage of tomato development and begin as small, water-soaked spots or circular grayish-white spots on the underside of older leaves; spots have a grayish center and a dark margin and they may colasece; fungal fruiting bodies are visible as tiny black specks in the center of spot; spots may also appear on stems, fruit calyxes, and flowers",
        causes: "Fungus",
        comments: "Spread by water splash; fungus overwinters in plant debris.",
        management: "Ensure all tomato crop debris is removed and destroyed in Fall or plowed deep into soil; plant only disease-free material; avoid overhead irrigation; stake plants to increase air circulation through the foliage; apply appropriate fungicide if necessary.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/3653/file/default-aeb92b2bc3b11475512a9271e74b72d6.jpg",
    },
    {
        diseases: "Verticillium wilt",
        symptoms: "Symptoms appear first on lower leaves and spread upwards; initial symptoms of the disease may be visible as yellow blotches on the lower leaves of the plant; a rapid yellowing of leaves follows as the disease progresses; leaf veins turn brown and brown dead spots appear on the leaves; leaves may wilt then die and drop from the plant; the disease progresses upwards through the stem causing the plant to be stunted; leaves at the top of the plant remain green; fruits develop yellow shoulders and yield is reduced; loss of leaves results in fruit being susceptible to sun scald.",
        causes: "Fungus",
        comments: "Fungi survive in crop debris in soil; disease emergence favors cool weather.",
        management: "Plant resistant varieties; sanitize all equipment on a regular basis; rotate with non-susceptible crops.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/4147/file/default-394102fda04dc2906e0e31bde2f976ce.jpg",
    },

    {
        diseases: "Target Spot",
        symptoms: "The fungus infects all parts of plant. Infected leaves shows small, pinpoint, water soaked spots initially. As the disease progress the spots enlarge to become necrotic lesions with conspicuous concentric circles, dark margins and light brown centers. Whereas the fruits exhibit brown, slightly sunken flecks in the beginning but later the lesions become large pitted appearance.",
        causes: "Fungus",
        comments: "The pathogen infects cucumber, pawpaw , ornamental plants, some weed species etc. The damaged fruits are susceptible for this disease.",
        management: "Remove the plant debris and burn them. Avoid over application of nitrogen fertilizer. If the disease is severe spray suitable fungicides.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/63624/file/default-208bb80eee23de1b57c0d5c91783ae18.jpg",
    },
    {
        diseases: "Bacterial",
        symptoms: "Bacterial canker can affect tomato plants of any age, seedlings may be killed quickly once they become infected; initial symptoms of bacterial canker is the unilateral wilting of plants and formation of light colored streaks up and down the outside of the leaf midrib, petiole and stem; streaks on stems may break open to form cankers; mature leaves develop small necrotic spots on the upper leaf surfaces or small raised white spots on the leaves; white spots develop on fruit, usually while they are still green; spots on fruit develop a raised dark center ",
        causes: "Bacterium",
        comments: "Can cause serious crop losses",
        management: "Plant only certified seed and transplants; hot water treatment of seed to remove bacteria; rotate crops with non-host plants; turn crops into soil after harvest to promote decomposition",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/4113/file/default-ab10856f4e76f079be9ced966e8851df.jpg",
    },
    {
        diseases: "Bacterial speck ",
        symptoms: "Dark specks appear on the leaves, often associated with a yellow halo; foliar symptoms of bacterial speck are very difficult to distinguish from bacterial spot but can be differentiated by symptoms on the fruit; lesions on fruit are much smaller than those caused by bacterial spot; lesions on fruit are raised and scaly",
        causes: "Bacterium",
        comments: "Disease emergence favors cool, moist weather.",
        management: "Do not plant in same area in successive years; use only high quality, disease-free seed and transplants; protective sprays of copper can help to reduce incidence of the disease.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/1162/file/default-507c87e051c94752e9561d77d89d4ae0.jpg",
    },
    {
        diseases: "Bacterial spot",
        symptoms: "Initial symptoms of the disease is the wilting of a few of the youngest leaves; the disease progresses rapidly in hot weather and the entire plant wilts suddenly and dies; in cooler conditions, wilting is less rapid and plant may produce roots on the stems; vascular tissue shows a brown discoloration and decaying roots; stems cut under water will ooze bacterial exudate and will confirm the symptoms are not caused by Fusarium wilt.",
        causes: "Bacterium",
        comments: "Bacterial wilt can cause complete destruction of the crop under conditions suitable for the spread of the soil-borne bacterium; disease causes serious losses in tomatoes grown in tropical and subtropical regions.",
        management: "Cultural practices may help to reduce incidence of the disease, rotate tomato with other, non-susceptible crops; avoid over-watering plants.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/4127/file/default-29657a486b63976a6e31ef701618c270.jpg",
    },
    {
        diseases: "Catface",
        symptoms: "Catface usually occurs on the blossom end, tomato fruits are usually misshapen with large holes or corky brown scars close to the blossom end of the fruit; fruits are often flattened and may be kidney shaped; holes on the fruit extend deep inside the fruit.",
        causes: "Physiological disorder",
        comments: "The catface deformity is possibly caused by internal or external changes that occurs during the formation of the flower resulting in the abnormal development of the fruit; the exact cause is unknown, there may be several factors in fruit deformation; cold weather is known to be a factor along with extreme fluctuations in temperatures between day and night; hormone based herbicides may also cause catfacing; varieties that produce large tomatoes are more prone to catfacing.",
        management: "Avoid pruning tomato plants excessively; avoid excessive fertilization with nitrogen which promotes rapid vegetative growth; if growing tomatoes in a glasshouse, provide the plants with heat to prevent temperatures dropping to damaging levels, particularly at night.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/4191/file/default-e20331101d3cffdab03524e7c739ddaa.jpg",
    },
    {
        diseases: "Edema (Oedema)",
        symptoms: "Swellings and/or blisters or calluses on leaves caused by rupturing epidermal and inner leaf cells ; deformed foliage which curls; leaf tissue may also tear as the leaf matures; symptoms are often mistaken for disease or insect damage",
        causes: "Physiological disorder",
        comments: "Edema occurs when water is absorbed from the soil faster than it can be transpired through the leaves and is caused by soil being warmer than the surrounding air",
        management: "Tomato plants should always be planted in well draining soil or potting media; avoid overwatering tomato plants, particularly during periods of low light and cool temperatures; if growing tomatoes in a glasshouse then anything that can be done to increase drainage and air circulation will be helpful in preventing edema; reduce humidity in the glasshouse in the morning by venting the house (heat may need to be turned up during this period depending on outdoor temperatures)",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/4312/file/default-81a20f400016776e3880e76da7687495.jpg",
    },
    {
        diseases: "Fertilizer burn",
        symptoms: "Symptoms may first appear as slowed growth and wilting; leaf tips and margins turn brown; plants have a scorched appearance.",
        causes: "Excess nitrogen salts",
        comments: "Fertilizer burn is usually caused by an excess of nitrogen salts in the soil which causes an osmotic stress on the plant tissues. The tissues dry out and die resulting in the characteristic scorched appearance of the leaves.",
        management: "Apply appropriate dose of fertilizer for the particular soil in which the plants are growing - nutrient requirements can be ascertained with a soil test; if liquid fertilizer was used, symptoms may be reversed by watering the plants heavily to leach some of the salts from the soil.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/4191/file/default-e20331101d3cffdab03524e7c739ddaa.jpg",
    },
    {
        diseases: "Little leaf",
        symptoms: "Little leaf symptoms include interveinal chlorosis of young leaves, distortion and failure of leaves along the midrib to expand, radial cracks of fruits extending from the calyx to the blossom scar and failure of blooms to set; symptoms progress to increased leaflet distortion and more pronounced interveinal chlorosis.",
        causes: "Physiological disorder",
        comments: "Three conditions appear to pre-dispose plants to little leaf. 1) high soil temperatures 2) high soil moisture and 3) presence of predisposing population of bacterial/fungal microorganisms in the soil.",
        management: "Little leaf is usually associated with water-logged areas of fields, subsequent drying out of affected areas usually resolves the problem and subsequent plant growth is normal; controlling the soil pH may also help the problem.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/4873/file/default-a6a5796426c3de95510642510454dc3e.jpg",
    },
    {
        diseases: "Magnesium deficiency",
        symptoms: "Symptoms of magnesium deficiency appear on older leaves first; initial symptoms are interveinal chlorosis of the leaves and, occasionally, a purple tinge to the leaves; as the deficiency becomes more severe, leaves may appear white with green veins; severe deficiencies may lead to reduced fruit yield.",
        causes: "Physiological disorder",
        comments: "Magnesium deficiency is rare in field grown tomatoes but occurs more frequently in soilless tomato culture.",
        management: "Magnesium deficiency can be prevented in tomato by applying dolomite lime to the soil, if an increase in soil pH is required, or through applications of a fertilizer containing magnesium.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/5037/file/default-454c444438c4da243b2e5184cc7ea565.jpg",
    },

    {
        diseases: "Nitrogen deficiency",
        symptoms: "Affected plants are smaller in size and grow less vigorously than healthy plants; symptoms appear on older leaves first; tomato leaves exhibit a general yellowing occasionally accompanied by purple leaf veins; plants possess thinner stems and fruit is smaller than healthy plants; fruits may be misshapen with a lighter red color than healthy plants.",
        causes: "Nutritional disorder",
        comments: "Nitrogen deficiency usually arises in tomato plantations through inadequate fertilizer application; heavy rain can leach nitrogen from sandy soils.",
        management: "If detected early, symptoms of nitrogen deficiency can be treated by applying appropriate amounts of nitrogen fertilizer.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/5037/file/default-454c444438c4da243b2e5184cc7ea565.jpg",
    },
    {
        diseases: "Phosphorous deficiency",
        symptoms: "Growth of tomato seedlings is reduced compared with healthy plants; leaves appear darker green and may have a purple tinge; in older tomato plants, leaves grow upright and appear light green on the upper surface and purple on the lower surface; symptoms appear on older leaves first.",
        causes: "Nutritional disorder",
        comments: "Phosphorous deficiency is rare in soils that are already used for agricultural purposes; in field grown tomatoes phosphorous deficiency more commonly appears in newly cleared land which has never been used to grow crops; phosphorus deficiency may occur on soilless tomato cultures if applications of the nutrient are inadequate.",
        management: "Soil levels of phosphorous should be measured prior to planting to determine the appropriate application for the particular site; phosphorous should be applied to the soil prior to planting if required as applications made after the onset of tomato growth are not usually successful in preventing symptoms.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/5037/file/default-454c444438c4da243b2e5184cc7ea565.jpg",
    },
    {
        diseases: "Potassium deficiency",
        symptoms: "Affected plants are smaller than healhty plants with smaller fruits and reduced yields; tomato leaves exhibit bronzing, older plant leaves turn tan and then brown at the margins; if deficiency is prolonged, leaves become necrotic at the margins and turn yellow between leaf veins.",
        causes: "Nutritional disorder",
        comments: "Potassium deficiency is usually caused by an inadequate fertilization, it is more common in sandy soils where the nutrient is easily leached from the soil by heavy rainfall.",
        management: "Potassium deficiency can be corrected through applications of the nutrient as a side dressing and/or through an irrigation system.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/5037/file/default-454c444438c4da243b2e5184cc7ea565.jpg",
    },
    {
        diseases: "Sunscald",
        symptoms: "Symptoms of sunscald are most common on green fruit; white or yellow necrotic patches develop on the sides of the fruit that are facing the sun; blisters may be white with a yellow halo; damaged areas may become flattened in appearance and papery in texture; damaged areas are often invaded by secondary pathogens and turn black.",
        causes: "Physiological disorder",
        comments: "Sunscald is common on plants which have been moved suddenly from a shaded location to full sun.",
        management: "Healthy plants with full foliage are less susceptible to sunscald as the leaves provide fruits with shading, ensure plants are watered regularly and fertilized adequately; use shade cloth to protect the fruits from the sun; control diseases that develop to prevent defoliation which can lead to sunscald.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/63675/file/default-80db1a04d80292b42cd4c569bf78d5e0.jpg",
    },
    {
        diseases: "Water stress",
        symptoms: "Leaves are green but wilting; leaves roll downwards and eventually drop from the plant; fruits may develop symptoms of Blossom-end rot ",
        causes: "Physiological stress",
        comments: "It is important to distinguish between plants that are temporarily wilted on hot days and those that are stressed due to lack of moisture in the soil; on very hot days tomato plants will wilt as the rate of transpiration exceeds the rate at which water can be taken up from the soil by the roots and the plants will usually recover in the evening when temperatures are cooler.",
        management: "Tomato plants should be watered deeply and evenly to avoid water stress; aim to keep the soil moist but not wet; allow the top of the soil to dry before watering again.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/63713/file/default-6932098c33f3074ac56b3991775ee036.jpg",
    },
    {
        diseases: "Zippering",
        symptoms: "Thin brown scars extending longutudinally from the petiole to the blossom-end of the fruit; each scar has smaller scars crossing it tranversely rendering it zipper-like in appearance; holes may open on along the scarred area.",
        causes: "Physiological stress",
        comments: "Zipper scars on tomato fruit are most prevalent in cool weather.",
        management: "The most effective method of preventing zippering is to grow tolerant varieties; when growing tomatoes in the glasshouse, appropriate temperatures should be maintained.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/4876/file/default-f61010dd2c2dc29d9e4f784a698e1988.png",
    },

    {
        diseases: "Oomycete",
        symptoms: "Buck eye rot of tomato initially appears as a brown spot on the fruit which enlarges over the fruit surface and forms concentric rings; the lesions may eventually cover up to half of the fruit and the flesh develops a soft rot underneath the skin; green or red fruits can be affected and disease often develops where fruit is in contact with the soil; white cottony growth may be visible in the centers of affected regions; spots enlarge and form large concentric ring shaped symptoms which are usually brown in color with sunken edges; the Phytophthora pathogen also causes root rot; young plants may exhibit a white cottony growth at crown of the plant and begin to wilt as the damage to the roots progresses; Phytophthora root rot can cause severe destruction of plant roots and cause the plants to wilt completely.",
        causes: "Fungi",
        comments: "Prolonged period of warm wet conditions favor disease occurrence; heavy soil saturation also favors disease development in soils where pathogen is present; disease can be spread by splashing water.",
        management: "Cultural control methods such as mulching around the plants and practicing rotation away from tomato can help to reduce losses from the disease; fungicides applied for the control of late blight also help to control the development of buckeye rot; solarizing or fumigating soil can help to reduce levels of inoculum.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/4185/file/default-b87d894dad939904ddd9e00a387a7cd9.jpg",
    },
    {
        diseases: "Late blight ",
        symptoms: "Late blight affects all aerial parts of the tomato plant; initial symptoms of the disease appear as water-soaked green to black areas on leaves which rapidly change to brown lesions; fluffy white fungal growth may appear on infected areas and leaf undersides during wet weather; as the disease progresses, foliage becomes becomes shriveled and brown and the entire plant may die; fruit lesions start as irregularly shaped water soaked regions and change to greasy spots; entire fruit may become infected and a white fuzzy growth may appear during wet weather.",
        causes: "Oomycete",
        comments: "Can devastate tomato plantings.",
        management: "Plant resistant varieties; if signs of disease are present or if rainy conditions are likely or if using overhead irrigation appropriate fungicides should be applied.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/4153/file/default-f5bb3474742e3b0525ef9e66967a7ec5.jpg",
    },
    {
        diseases: "Viral",
        symptoms: "Symptoms can occur at any growth stage and any part of the plant can be affected; infected leaves generally exhibit a dark green mottling or mosaic; some strains of the virus can cause yellow mottling on the leaves; young leaves may be stunted or distorted; severely infected leaves may have raised green areas; fruit yields are reduced in infected plants; green fruit may have yellow blotches or necrotic spots; dark necrotic streaks may appear on the stems, petioles leaves and fruit",
        causes: "Virus",
        comments: "ToMV is a closely related strain of Tobacco mosaic virus (TMV), it enters fields via infected weeds, peppers or potato plants; the virus may also be transmitted to tomato fields by grasshoppers, small mammals and birds.",
        management: "Plant varieties that are resistant to the virus; heat treating seeds at 70°C (158°F) for 4 days or at 82–85°C (179.6–185°F) for 24 hours will help to eliminate any virus particles on the surface of the seeds; soaking seed for 15 min in 100 g/l of tri-sodium phosphate solution (TSP) can also eliminate virus particles - seeds should be rinsed thoroughly and laid out to dry after this treatment; if the virus is confirmed in the field, infected plants should be removed and destroyed to limit further spread; plant tomato on a 2-year rotation, avoiding susceptible crops such as peppers, eggplant, cucurbits and tobacco; disinfect all equipment when moving from infected areas of the field.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/63694/file/default-0e281ebc682d3f01c011a93828688493.jpg",
    },
    {
        diseases: "Tomato spotted wilt ",
        symptoms: "Infected plants exhibit bronzing or purpling of the upper sides of young leaves and develop necrotic spots; leaf spots may resemble those caused by bacterial spot, but a bacterial ooze test will be negative; leaves may cup downwards, shoot tips may begin to die back; symptoms on ripe fruit appear as chlorotic spots and blotches, often with concentric rings; ring spot symptoms vary with different tomato cultivars; irregular ripening caused by TSWV can also show up when fruit are treated with ethylene gas; green fruit may exhibit slightly raised areas with faint concentric zonation.",
        causes: "Virus",
        comments: "TSWV infects numerous ornamentals, vegetables, field crops and weeds; virus is vectored by at least eight species of thrips; thrips, acquires the virus during the larval stages,and transmit the virus when they are adults.",
        manage: "Control populations of western flower thrips and onion thrips",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/4166/file/default-a690c1d667013d117face5ddb2f5b18b.jpg",
    },
    {
        diseases: "Tomato Yellow Leaf Curl disease",
        symptoms: "The infected leaves become reduced in size, curl upward, appear crumpled and show yellowing of veins and leaf margins. The internodes become shorter and whole plant appear stunted and bushy. The whole plant stand erect with only upright growth. The flowers may not develop and drop off.",
        causes: "Virus",
        comments: "The virus is transmitted by white flies and may cause 100 % yield loss if the plants infect at early stage of crop. The virus also infect other hosts like common bean, ornamental plants and several weed species.",
        management: "Grow available resistant varieties. Transplant only disease and whiteflies free seedlings. Remove the infected plants and burn them. Keep the field free from weeds. Use yellow sticky traps to monitor and control whiteflies. If the insect infestation is severe spray suitable insecticides.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/63706/file/default-55de8a06adec8ab179777a8afd45abaa.jpg",
    },
    {
        diseases: "Pests",
        symptoms: "Small soft bodied insects on underside of leaves and/or stems of plant; usually green or yellow in color, but may be pink, brown, red or black depending on species and host plant; if aphid infestation is heavy it may cause leaves to yellow and/or be distorted, necrotic spots on leaves and/or stunted shoots; aphids secrete a sticky, sugary substance called honeydew which encourages the growth of sooty mold on the plants.",
        causes: "Insects",
        comments: "Distinguishing features of aphids include the presence of cornicles (tubular structures) which project backwards from the insect's body; aphids will generally not move very quickly when disturbed; aphids may also transmit plant viruses to the plant when they feed.",
        management: "If aphid population is limited to just a few leaves or shoots then the infestation can be pruned out to provide control; check transplants for aphids before planting; use tolerant varieties if available; reflective mulches such as silver colored plastic can deter aphids from feeding on plants; sturdy plants can be sprayed with a strong jet of water to knock aphids from leaves; insecticides are generally only required to treat aphids if the infestation is very high - plants generally tolerate low and medium level infestation; insecticidal soaps or oils such as neem or canola oil are usually the best method of control; always check the labels of the products for specific usage guidelines prior to use.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/63641/file/default-657112bc7cd5b7a69de95ad950402af5.jpg",
    },
    {
        diseases: "Beet armyworm",
        symptoms: "Singular, or closely grouped circular to irregularly shaped holes in foliage; heavy feeding by young larvae leads to skeletonized leaves; shallow, dry wounds on fruit; egg clusters of 50-150 eggs may be present on the leaves; egg clusters are covered in a whitish scale which gives the cluster a cottony or fuzzy appearance; young larvae are pale green to yellow in color while older larvae are generally darker green with a dark and light line running along the side of their body and a pink or yellow underside.",
        causes: "Insects",
        comments: "Insect can go through 3-5 generations a year.",
        management: "Organic methods of controlling the beet armyworm include biological control by natural enemies which parasitize the larvae and the application of Bacillus thuringiensis; there are chemicals available for commercial control but many that are available for the home garden do not provide adequate control of the larvae.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/1203/file/default-be1788a7f6c2a42da749576930e59df5.jpg",
    },
    {
        diseases: "Colorado potato beetle",
        symptoms: "Feeding damage to foliage; if infestation is severe or if left untreated plants can be completely defoliated; adult insect is a black and yellow striped beetle; larvae are bright red with black heads when they first hatch and change color to pink; larvae have two rows of black spots.",
        causes: "Insects",
        comments: "Adult beetles emerge in spring; female beetles lay eggs in batches of up to two dozen; eggs are orange-yellow and are laid on undersides of leaves; a female can lay 500 or more eggs over a four to five week period.",
        management: "Control of Colorado potato beetle can be challenging as they have developed high levels of insecticide resistance; adults and larvae should be hand picked from plants and destroyed in soapy water; applications of Bacillus thuringiensis can be effective at controlling larvae but should be applied frequently; some insecticides, including spinosad, are still effective against adult beetles.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/63648/file/default-271e0eae84f0062e8d2326db0def4727.jpg",
    },
    {
        diseases: "Cutworms",
        symptoms: "Stems of young transplants or seedlings may be severed at soil line; if infection occurs later, irregular holes are eaten into the surface of fruits; larvae causing the damage are usually active at night and hide during the day in the soil at the base of the plants or in plant debris of toppled plant; larvae are 2.5–5.0 cm (1–2 in) in length; larvae may exhibit a variety of patterns and coloration but are usually dirty gray or brown to black with dark spots or lines and will curl up into a characteristic C-shape when disturbed",
        causes: "Insects",
        comments: "Cutworms have a wide host range and attack vegetables including asparagus, bean, cabbage and other crucifers, carrot, celery, corn, lettuce, pea, pepper, potato and tomato",
        management: "Remove all plant residue from soil after harvest or at least two weeks before planting, this is especially important if the previous crop was another host such as alfalfa, beans or a leguminous cover crop; plastic or foil collars fitted around plant stems to cover the bottom 3 inches above the soil line and extending a couple of inches into the soil can prevent larvae severing plants; hand-pick larvae after dark; spread diatomaceous earth around the base of the plants (this creates a sharp barrier that will cut the insects if they try and crawl over it); apply appropriate insecticides to infested areas of garden or field if not growing organically",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/1207/file/default-a26b1bae2b60855bba7553e0e2024be0.jpg",
    },
    {
        diseases: "Flea beetles",
        symptoms: "Small, dark colored beetles; adults are 1/8 inch long; larvae are 1/4 inch long; adults and larvae feed on foliage and flowers; larvae feed on roots and tubers; adults and larvae are generally found in the soil.",
        causes: "Insects",
        comments: "Flea beetles are active year round.",
        management: "Hand pick adults and larvae from plants; use reflective mulches such as silver colored plastic to deter flea beetles from feeding on plants; use tolerant varieties if available; apply appropriate insecticides to infested areas of garden or field if not growing organically.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/63652/file/default-ac95f46879967bf7f186afd7f646ad39.jpg",
    },
    {
        diseases: "Hornworms (Tomato hornworm, Tobacco hornworm)",
        symptoms: "Feeding damage to leaves or leaves stripped from plant; heavy infestation may result in damage to fruit appearing as large open scars; large green caterpillars may be spotted on plant; caterpillars may reach in excess of 7.5 cm (3 in) in length and possess a spike at the end of their body; most common species have 7 diagonal stripes on sides or 8 v-shaped markings on each side; single eggs may be present on leaves and measure approx 1.3 mm in diameter; eggs are in initially light green in color and turn white prior to hatching.",
        causes: "Insects",
        comments: "Insect overwinters as pupa in soil; typically undergoes 2 generations per year; heavy infestations are more common in warm areas.",
        management: "Hand pick larvae from plants leaving any parasitized larvae behind to promote populations of natural enemies (these larvae can be distinguished by the presence of white, oblong-shaped cocoons on their backs); sprays of Bacillus thuringiensis are organically acceptable and highly effective.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/63665/file/default-5306924de86a1bbd5e57b950a767749f.jpg",
    },
    {
        diseases: "Leafminers",
        symptoms: "Thin, white, winding trails on leaves; heavy mining can result in white blotches on leaves and leaves dropping from the plant prematurely; early infestation can cause fruit yield to be reduced; adult leafminer is a small black and yellow moth which lays its eggs in the leaf; larvae hatch and feed on leaf interior.",
        causes: "Insects",
        comments: "Insect overwinters as pupa in soil; typically undergoes 2 generations per year; heavy infestations are more common in warm areas.",
        management: "Leafminer natural enemies normally keep populations under control; check transplants for signs of leafminer damage prior to planting; remove plants from soil immediately after harvest if making new plantings in same place or close by; keep the field free from weeds especially Solanum, Datura, Nicotiana; use pheromone traps and white sticky traps to monitor and control insect;only use insecticides when leafminer damage has been identified as unnecessary spraying will also reduce populations of their natural enemies.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/62538/file/default-64cefc6d20018775329221143a28779a.jpg",
    },
    {
        diseases: "Loopers",
        symptoms: "Large or small holes in leaves; damage often extensive; caterpillars are pale green with a white lines running down either side of their body; caterpillars are easily distinguished by the way they arch their body when moving; eggs are laid singly, usually on the lower leaf surface close to the leaf margin, and are white or pale green in color.",
        causes: "insect",
        comments: "Insects overwinter as pupae in crop debris in soil; adult insect id a dark colored moth; caterpillars have a wide host range.",
        management: "Looper populations are usually held in check by natural enemies; if they do become problematic larvae can be hand picked from the plants; an organically acceptable control method is the application of Bacillus thuringiensis which effectively kills younger larvae; chemical sprays may also damage populations of natural enemies and should only be considered if sunburn of fruit is likely.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/63669/file/default-e1fd4b5d9d37c2e4250179b18d1cdef6.jpg",
    },
    {
        diseases: "Stinkbugs (Various)",
        symptoms: "Dark colored pinpricks on fruit surrounded by a lighter area that turns yellow or remains light green; stink bugs often carry pathogens in their mouthparts which can cause secondary infections and decay of fruit; adult insect is shield-shaped and brown or green in color; may have pink, red or yellow markings; eggs are drum shaped and laid in clusters on the leaves; larvae resemble the adults but are smaller.",
        cause: "insect",
        comments: "Several types of stink bug can cause damage to tomatoes; adult insects overwinter under leaves, on legumes, blackberries or on certain weeds such as mustard or Russian thistle.",
        management: "Remove weeds around crop which may act as overwintering sites for stink bugs and practice good weed management throughout the year; organically accepted control methods include the use of insecticidal soaps, kaolin clay and preservation of natural enemies; chemical treatments are not recommended for tomatoes that are to be processed for paste or canning unless secondary infections with other pathogens are a concern.",
        url: "https://plantvillage-production-new.s3.amazonaws.com/image/1206/file/default-7c06b3e7c44d4651afc084b7701a9d03.jpg",
    },
];